### ISSUE TITLE
Release of GHC 7.10.3 in PPA? Mistake?

### ISSUE THREAD

**Issue by Blaisorblade** [hvr/multi-ghc-travis#30]
Your PPA contains a confusing release of GHC 7.10.3. I just installed it (ignoring on purpose the odd version number), then learned it isn't released yet...

Specifically, it's package ghc-7.10.3 on https://launchpad.net/~hvr/+archive/ubuntu/ghc, package version 7.10.2-XXX.

**Comment by hvr** [comment]
It was deliberate but it's just a snapshot from the `ghc-7.10` branch which will eventually become GHC 7.10.3.  It's there so people can test early and/or see if some bug is still present in the stable branch.

The [versioning scheme](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/version-numbering.html) corresponds to GHC stable snapshots, i.e. "GHC 7.10.2.yyyymmdd". The package name is chosen in a way so that the snapshots turns into a final 7.10.3 release seamless (to reduce the number of `.travis.yml` edits)

**Comment by Blaisorblade** [comment]
Thanks for the clarification! (I won't close the issue myself, in case you want to update docs before closing it).

**Comment by hvr** [comment]
We've got a 7.10.3 RC now, so this issue is moot now :-)
