### ISSUE TITLE
GHC 7.10/8.0 noticeably slower

### ISSUE THREAD

**Issue by mvdan** [hvr/multi-ghc-travis#48]
I use your apt repos to build and test a library on GHC 7.6 through 8.0.

All works well, except for the fact that there seems to be a very noticeable slowdown on 7.10. Examples:
- https://travis-ci.org/mvdan/hint/builds/134009666
- https://travis-ci.org/mvdan/hint/builds/133981168

I can understand a slight slowdown between releases, as the compiler perhaps gets bigger and does more work. And this happens between 7.6-7.8 and 7.10-8.0. But between 7.8-7.10, the runtime is almost multiplied by 10. `cabal build` jumps from ~15s to more than 450s, which is weird.

I can't see any obvious mistakes or causes on my end, so perhaps it has to do with how newer GHC versions were built in your apt repo?

Any pointers appreciated.

**Comment by dolio** [comment]
7.10 and 7.8 are dramatically slower on some code than prior versions. Same is probably true of 8.0. For instance, vector's test suite is disabled on 7.10.3, because it cannot build on travis (and on my local machine, it takes many gigabytes of memory). So this is probably a GHC problem you're seeing.

If you don't see it locally, take a look at memory usage while compiling. vector on 7.10.3 compiles relatively quickly on my machine, but it uses extreme amounts of memory. Since travis VMs have much less memory, this translates to much more garbage collection, and slower builds than you'd see in your dev environment.

**Comment by hvr** [comment]
Fwiw, a useful GHC flag is `-Rghc-timing` which dumps single-line stats about mem-usage & processing time.

**Comment by mvdan** [comment]
I was fearing that GHC would be to blame. I was hoping that it was some GHC build flag or setting that @hvr was using, and that this would be fixable in his debian repo.

@hvr since that isn't the case, feel free to close this issue. I don't see anything else to be done here, other than perhaps tuning GHC (or Travis?) for the memory usage stuff that @dolio mentioned.

**Comment by mvdan** [comment]
No interest, so closing.
